name: deploy
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and Static HTML Export
        run: npm run build

      - name: Disable Jekyl # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
        run: touch ./out/.nojekyll

      - name: Enable custom domain
        run: cp CNAME ./out

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: out
